---
title: "Introduction to  downloadthis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to  downloadthis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This package provides a wrapper around `bsplus::bs_button()`, which has to goal to provide a download button in HTML outputs from R Markdown without the need to have `runtime: shiny`.

You can easily produce a download button as follows:

## Button

### Default

```{r example_1}
library(downloadthis)

mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "default",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

### Primary

```{r example_2}
mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".xlsx",
    button_label = "Download data as xlsx",
    button_type = "primary",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

### Success

```{r example_3}
mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "success",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

### Info

```{r example_4}
mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".xlsx",
    button_label = "Download data as xlsx",
    button_type = "info",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

### Warning

```{r example_5}
mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".csv",
    button_label = "Download data as csv",
    button_type = "warning",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```

### Danger

```{r example_6}
mtcars %>% 
  download_this(
    output_name = "mtcars dataset",
    output_extension = ".xlsx",
    button_label = "Download data as xlsx",
    button_type = "danger",
    has_icon = TRUE,
    icon = "fa fa-save"
  )
```
